version: "3.9"

services:
    machine:
        build:
            context: $HOME/repo/node_course/practice_one/
            dockerfile: $HOME/repo/node_course/local_deploy/Dockerfile
        volumes:
            - $HOME/repo/node_course/practice_one/:/code
            - /code/node_modules
        ports:
            - "4000:4000"
        networks:
            - mynetwork

    db:
        build:
            context: .
            dockerfile: $HOME/repo/node_course/local_deploy/Dockerfile_mongo
        container_name: mongo
        restart: always
        env_file:
            - $HOME/repo/node_course/practice_one/.env
        volumes:
            - ../db2:/data/db
        ports:
            - "27017:27017"
        networks:
            - mynetwork  

networks:
    mynetwork:
        driver: bridge
